Feature/ner
YouTubeNLP/Backend pull request #33
Opened 2020-08-19 15:34 UTC by YashSahsani

# Pull Request Template

## Description

1)Added ner endpoint.
2)Added test for the same.
3)Added necessary Documentation
4)Added Production docker file 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested? (Optional)

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked my code and corrected any misspellings
![image](https://user-images.githubusercontent.com/48834282/90653421-c77dcb00-e25c-11ea-99f3-42c71849695a.png)
![image](https://user-images.githubusercontent.com/48834282/90653493-e1b7a900-e25c-11ea-82b8-efa22e2551b1.png)

2020-08-20 05:33 UTC, pandevim requested changes

2020-08-20 05:33 UTC, pandevim commented on src/v1/service/Ner/ner.py
> +	"""
We don't have to mention the whole code. Only a url would suffice.
```suggestion
# https://github.com/YouTubeNLP/NLP/tree/master/ner
```

2020-08-20 05:33 UTC, pandevim commented on README.md
> +$ docker build -t ynlp .\
Can you explain what the `.\` do here?

2020-08-20 05:35 UTC, YashSahsani commented on README.md
> +$ docker build -t ynlp .\
Its just for new line.

2020-08-20 06:05 UTC, pandevim commented on src/v1/service/Ner/ner.py
> +	def save_file(self,document_name, transcript):
Is saving a file doing any help in our process here?

2020-08-20 06:10 UTC, pandevim commented on src/v1/service/Ner/ner.py
> +	    ner_spacy = self.spacy_ner(video_transcript)
If we're only using `nerd` why define `spacy` function and use it at all?
`
```suggestion

```

2020-08-20 06:41 UTC, pandevim requested changes
Also can you use a decent `videoId` for response screenshots?
Our service are primarily for political videos and not for music videos. So you can use the `videoId` suggested in the Backend [README.md](https://github.com/YouTubeNLP/Backend/blob/dev/README.md).

Also the structure of the response needs to change a little bit. Currently it's like this:
```json
[
  [ "entity", "label1" ],
  [ "entity", "label2" ],
  [ "entity", "label3" ]
]
```
We want it to be more compatible with the original schema which is decided. That is present in the [API Reference](https://app.swaggerhub.com/apis-docs/youtubenlp/backend/0.0.1#/default/get_ner__videoId_). That is:
```json
{
	"video_id": "video_id",
	"entities": [
		{
			"label1": "label",
			"text": [
				"string1",
				"string2",
				"string3"
			]
		},
		{
			"label2": "label",
			"text": [
				"string1",
				"string2",
				"string3"
			]
		},
		{
			"label3": "label",
			"text": [
				"string1",
				"string2",
				"string3"
			]
		}
	]
}
```
Also remember

2020-08-20 06:46 UTC, pandevim commented on README.md
> +$ docker build -t ynlp .\
Would you mind to explain how this is better than the previous one?

2020-08-20 06:58 UTC, YashSahsani commented on README.md
> +$ docker build -t ynlp .\
if I don't put \ at the end of the line all the three commands are printed in one line.

2020-08-20 08:50 UTC, YashSahsani commented
![image](https://user-images.githubusercontent.com/48834282/90748795-44a65000-e2f0-11ea-870e-931f31903a96.png)

2020-08-20 10:19 UTC, YashSahsani commented
![image](https://user-images.githubusercontent.com/48834282/90758490-be443b00-e2fc-11ea-97df-c72149c41e8e.png)

2020-08-20 11:27 UTC, pandevim approved these changes
Nice work!

2020-08-20 11:28 UTC, merged

2020-09-04 15:56 UTC, pandevim commented on src/main.py
> +                ners["entity"][label_num-1]["text"].append(text)
@YashSahsani 
My apologies this slipped my review before, but this logic is suppose to be inside the `Ner` service directory.